### ISSUE TITLE
牛牛怎么样做出牌局里面最小的牌呢

### ISSUE THREAD

**Issue by kevin-xk** [goodspb/poker-algorithm#1]
看了你的算法后，我也自己写了一份，但是我想做牌，现在遇到一个问题，我不知道怎么做出这一局中最小的牌，希望你能给指点下

**Comment by goodspb** [comment]
先将所有牌排序，然后看看最小的牌的牌型是什么，然后自己拼凑一个比这个更小的牌型即可
